# This is a basic workflow to help you get started with Actions

name: CI Test Package

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "CI"
  CI:
    env:
      db_name: silkyRoad
      db_user: root
      db_password: root
      db_port: 3307
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      
      - name: Set up dockerized mysql
        run: docker-compose -f docker/docker-mysql/docker-compose.yml up -d
        
          
      # Runs a single command using the runners shell
      - name: Run All Tests
        run: mvn -DAUTH_SERVICE_SECRET=something -DAUTH_SERVICE_IP=somethingelse -DAWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }} -DAWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }} test

      # Runs a set of commands using the runners shell
      - name: Stop dockerized mysql
        run: docker-compose -f docker/docker-mysql/docker-compose.yml down
